---
stages:
  - test

test:
  stage: test
  image: python:3.9-bullseye
  script:
    - pip install -r requirements.txt
    - pip install .
    - pip install pytest
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

